#!/usr/bin/env python
from build_utils import *

def build():
    mkdir('swfs')
    experiments()

def clean():
    rmdir('swfs')

def experiments():
    haxe('TestShader', libs=['format'])
    haxe('STest')

main()
