#!/usr/bin/env python
from build_utils import *

def build():
    build_assets('assets.Creatures', ['assets/bitmap/creatures/*'])
    mkdir('swfs')
    experiments()

def clean():
    rmdir('swfs')

def experiments():
    haxe('experiments.TestShader',           libs=['format'])
    haxe('experiments.TestSimplex')
    haxe('experiments.Zoomer',               libs=['polygonal'])
    haxe('experiments.explorer.Explorer',    libs=['polygonal'])
    haxe('experiments.Experiment')
    haxe('experiments.Exp2')
    haxe('experiments.Exp3')
    haxe('experiments.Game')
    haxe('experiments.game2.Game2')
    haxe('experiments.game2.Viewer',         libs=['sandy'])
    haxe('experiments.newexplorer.Explorer', libs=['polygonal'], assets=['assets.Creatures'])

main()
