#!/usr/bin/env python
from build_utils import *

def build():
    mkdir('swfs')
    #neworld()
    #explorer()
    #zoomer()
    simplex()

def clean():
    rmdir('swfs')
    pass


def simplex():
    haxe('STest')
    pass

main()
